language: node_js
node_js:
- 0.10.18
env:
- NODE_ENV=development
branches:
  only:
  - develop
before_install:
- ulimit -n 1024
install:
- npm install
- npm install -g grunt-cli
# TODO: move this into a grunt task properly like
- npm install -g myth
- bower install
script:
- echo "Running tests"
- ./node_modules/mocha-phantomjs/bin/mocha-phantomjs test/index.html
- grunt build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: PBJ38fdDq0rd2bIcWNb6DfUP7OI+ddwVoEE/XcfZ6BiLIohWhzde4JMX1hsb6Uk5Eaa7O+bMd8+22k7HFs8B+WBQ3wCYENFCtUpvdRPsRPzz0xT3zbJnRPbE+3hXBY2ZXAyR4myzTg/gT6Aw403dR++4fVsyoWGihOxVNMRKVJQ=
  app:
    develop: cottage-booking
  strategy: anvil
  # on:
  #   repo: RpprRoger/cottage-booking
  #   branch: develop
notifications:
  email:
    recipients:
    - karl@neontribe.co.uk
    - rob@neontribe.co.uk
    on_success: always
    on_failure: always
